### ISSUE TITLE
:fix: 수정된 api에 맞춰 수정

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42checkin_v3-backend#117]
## 필요 기능
- getTime~ 함수를 더하지 않고 배열로 반환하도록 수정 (0번째 배열이 최근)
- 주 단위 함수 일-토 를 월-일로 변경
---
- 함수 이름 변경 
  - getTagPerDay : 입력한 날짜의 페어가 맞는 로그 배열을 반환
  - getTagPerMonth : 입력한 월의 페어가 맞는 로그 배열을 반환
  - getAllTagPerDay : 입력한 날짜의 모든 로그 배열을 반환
  - getAllTagPerMonth : 입력한 월의 모든 로그 배열을 반환
---
- 기존 api 업데이트 : accumulationTimes
  - 최근 6주차의 총 체류 시간을 반환
  - 최근 6개월간의 총 체류 시간을 반환

## 연관 기능
- 리팩터링 및 api 수정

**Comment by niamu01** [comment]
todo: 날짜 계산 실수로 다음달 첫 로그가 들어오는 이슈 해결
