### ISSUE TITLE
:sparkles: 외부 링크로 리다이렉트 시켜주는 API 제작

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42checkin_v3-backend#130]
## 필요 기능
- 지원금 지침, 출입기능 문의 등의 링크는 변경될 우려가 있기 때문에 백앤드에서 해당 링크로 리다이렉트 해주기 위한 컨트롤러 생성
  - 지원금 지침 안내 : `/redirect/money_guidelines`
  - 출입기록 문의 : `/redirect/question`
  - 이용 가이드 : `/redirect/usage`
  - 앱 피드백 : `/redirect/feedback`

## 연관 기능
- 리다이렉트

**Comment by YunKi-H** [comment]
iOS '이용약관' (42networks) -> https://profile.intra.42.fr/legal/terms
공통 '재발급 신청 방법' -> 미정

**Comment by niamu01** [comment]
.env.sample 파일 수정..! 😮

**Comment by joohongpark** [comment]
일단 위 두 건 적용하겠습니다!

**Comment by joohongpark** [comment]
이슈의 건들 처리 완료하였습니다. 추가 요청이 필요하신 경우 해당 이슈를 다시 열어서 알려주세요 :)
